# NumPy Practice

This notebook offers a set of excercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
arr1 = np.array([2, 4, 6, 8, 10])

# Create a 2-dimensional NumPy array using np.array()
arr2 = np.array([[1, 3, 5],
                 [7, 9, 11]])

# Create a 3-dimensional Numpy array using np.array()
arr3 = np.array([[[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]],
                 [[10, 11, 12],
                  [13, 14, 15],
                  [16, 17, 18]]])

arr1, arr2, arr3

(array([ 2,  4,  6,  8, 10]),
 array([[ 1,  3,  5],
        [ 7,  9, 11]]),
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],
 
        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]]))

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [3]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
arr1.shape, arr1.dtype, type(arr1)

((5,), dtype('int64'), numpy.ndarray)

In [4]:
# Attributes of 2-dimensional array
arr2.shape, arr2.dtype, type(arr2)

((2, 3), dtype('int64'), numpy.ndarray)

In [5]:
# Attributes of 3-dimensional array
arr3.shape, arr3.dtype, type(arr3)

((2, 3, 3), dtype('int64'), numpy.ndarray)

In [6]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
arr2_df = pd.DataFrame(arr2)
arr2_df

0  1   2
0  1  3   5
1  7  9  11

In [7]:
# Create an array of shape (10, 2) with only ones
arr_ones = np.ones((10, 2))
arr_ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
# Create an array of shape (7, 2, 3) of only zeros
arr_zeros = np.zeros((7, 2, 3))
arr_zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [9]:
# Create an array within a range of 0 and 100 with step 3
arr_step3 = np.arange(0, 100, 3)
arr_step3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [10]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
arr_random_int = np.random.randint(0, 10, (7, 2))
arr_random_int

array([[3, 0],
       [1, 4],
       [2, 8],
       [9, 5],
       [3, 3],
       [9, 0],
       [3, 0]])

In [11]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
arr_random_float = np.random.random((3, 5))
arr_random_float

array([[0.55920002, 0.24655502, 0.20523681, 0.37956501, 0.63206735],
       [0.79417245, 0.01403278, 0.59413986, 0.81609447, 0.6413159 ],
       [0.18772346, 0.06381473, 0.93274307, 0.92891854, 0.08712111]])

In [12]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
arr_random_int_seeded = np.random.randint(0, 10, (4, 6))
arr_random_int_seeded

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [13]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
arr_random_numbers = np.random.randint(1, 10, (4, 6))

# Find the unique numbers in the array you just created
arr_random_numbers, np.unique(arr_random_numbers)

(array([[9, 1, 3, 7, 4, 9],
        [3, 5, 3, 7, 5, 9],
        [7, 2, 4, 9, 2, 9],
        [5, 2, 4, 7, 8, 3]]),
 array([1, 2, 3, 4, 5, 7, 8, 9]))

In [14]:
# Find the 0'th index of the latest array you created
arr_random_numbers[0]

array([9, 1, 3, 7, 4, 9])

In [15]:
# Get the first 2 rows of latest array you created
arr_random_numbers[:2]

array([[9, 1, 3, 7, 4, 9],
       [3, 5, 3, 7, 5, 9]])

In [16]:
# Get the first 2 values of the first 2 rows of the latest array
arr_random_numbers[:2, :2]

array([[9, 1],
       [3, 5]])

In [17]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
arr_random_numbers1 = np.random.randint(0, 10, (3, 5))
arr_ones1 = np.ones((3, 5))

arr_random_numbers1, arr_ones1

(array([[0, 3, 1, 7, 3],
        [1, 5, 5, 9, 3],
        [5, 1, 9, 1, 9]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [18]:
# Add the two arrays together
arr_random_numbers1 + arr_ones1

array([[ 1.,  4.,  2.,  8.,  4.],
       [ 2.,  6.,  6., 10.,  4.],
       [ 6.,  2., 10.,  2., 10.]])

In [19]:
# Create another array of ones of shape (5, 3)
arr_ones2 = np.ones((5, 3))
arr_ones2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
# Try add the array of ones and the other most recent array together
arr_random_numbers1 + arr_ones2.T

array([[ 1.,  4.,  2.,  8.,  4.],
       [ 2.,  6.,  6., 10.,  4.],
       [ 6.,  2., 10.,  2., 10.]])

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [21]:
# Create another array of ones of shape (3, 5)
arr_ones3 = np.ones((3, 5))
arr_ones3

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
# Subtract the new array of ones from the other most recent array
arr_random_numbers1 - arr_ones3

array([[-1.,  2.,  0.,  6.,  2.],
       [ 0.,  4.,  4.,  8.,  2.],
       [ 4.,  0.,  8.,  0.,  8.]])

In [23]:
# Multiply the ones array with the latest array
arr_random_numbers1 * arr_ones3

array([[0., 3., 1., 7., 3.],
       [1., 5., 5., 9., 3.],
       [5., 1., 9., 1., 9.]])

In [24]:
# Take the latest array to the power of 2 using '**'
arr_random_numbers1 ** 2

array([[ 0,  9,  1, 49,  9],
       [ 1, 25, 25, 81,  9],
       [25,  1, 81,  1, 81]])

In [25]:
# Do the same thing with np.square()
np.square(arr_random_numbers1)

array([[ 0,  9,  1, 49,  9],
       [ 1, 25, 25, 81,  9],
       [25,  1, 81,  1, 81]])

In [26]:
# Find the mean of the latest array using np.mean()
np.mean(arr_random_numbers1)

4.133333333333334

In [27]:
# Find the maximum of the latest array using np.max()
np.max(arr_random_numbers1)

9

In [28]:
# Find the minimum of the latest array using np.min()
np.min(arr_random_numbers1)

0

In [29]:
# Find the standard deviation of the latest array
np.std(arr_random_numbers1)

3.073904502239601

In [30]:
# Find the variance of the latest array
np.var(arr_random_numbers1)

9.44888888888889

In [31]:
# Reshape the latest array to (3, 5, 1)
arr_random_numbers1_reshaped = arr_random_numbers1.reshape((3, 5, 1))
arr_random_numbers1, arr_random_numbers1_reshaped

(array([[0, 3, 1, 7, 3],
        [1, 5, 5, 9, 3],
        [5, 1, 9, 1, 9]]),
 array([[[0],
         [3],
         [1],
         [7],
         [3]],
 
        [[1],
         [5],
         [5],
         [9],
         [3]],
 
        [[5],
         [1],
         [9],
         [1],
         [9]]]))

In [32]:
# Transpose the latest array
arr_random_numbers1_reshaped.T

array([[[0, 1, 5],
        [3, 5, 1],
        [1, 5, 9],
        [7, 9, 1],
        [3, 3, 9]]])

What does the transpose do?

In [33]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
arr_random_numbers2 = np.random.randint(0, 10, (3, 3))
arr_random_numbers3 = np.random.randint(0, 10, (3, 2))
arr_random_numbers2, arr_random_numbers3

(array([[3, 7, 6],
        [8, 7, 4],
        [1, 4, 7]]),
 array([[9, 8],
        [8, 0],
        [8, 6]]))

In [34]:
# Perform a dot product on the two newest arrays you created
np.dot(arr_random_numbers2, arr_random_numbers3)

array([[131,  60],
       [160,  88],
       [ 97,  50]])

In [35]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
arr_random_numbers4 = np.random.randint(0, 10, (4, 3))
arr_random_numbers5 = np.random.randint(0, 10, (4, 3))
arr_random_numbers4, arr_random_numbers5

(array([[8, 7, 0],
        [7, 7, 2],
        [0, 7, 2],
        [2, 0, 4]]),
 array([[9, 6, 9],
        [8, 6, 8],
        [7, 1, 0],
        [6, 6, 7]]))

In [36]:
# Perform a dot product on the two newest arrays you created
np.dot(arr_random_numbers4, arr_random_numbers5.T)

array([[114, 106,  63,  90],
       [123, 114,  56,  98],
       [ 60,  58,   7,  56],
       [ 54,  48,  14,  40]])

It doesn't work. How would you fix it?

In [37]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(arr_random_numbers4, arr_random_numbers5.T)

array([[114, 106,  63,  90],
       [123, 114,  56,  98],
       [ 60,  58,   7,  56],
       [ 54,  48,  14,  40]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [38]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
arr_random_numbers6 = np.random.randint(0, 10, (10, 5))
arr_random_numbers7 = np.random.randint(0, 10, (10, 5))
arr_random_numbers6, arr_random_numbers7

(array([[4, 2, 7, 5, 2],
        [0, 2, 4, 2, 0],
        [4, 9, 6, 6, 8],
        [9, 9, 2, 6, 0],
        [3, 3, 4, 6, 6],
        [3, 6, 2, 5, 1],
        [9, 8, 4, 5, 3],
        [9, 6, 8, 6, 0],
        [0, 8, 8, 3, 8],
        [2, 6, 5, 7, 8]]),
 array([[4, 0, 2, 9, 7],
        [5, 7, 8, 3, 0],
        [0, 9, 3, 6, 1],
        [2, 0, 4, 0, 7],
        [0, 0, 1, 1, 5],
        [6, 4, 0, 0, 2],
        [1, 4, 9, 5, 6],
        [3, 6, 7, 0, 5],
        [7, 4, 3, 1, 5],
        [5, 0, 8, 5, 2]]))

In [39]:
# Compare the two arrays with '>'
arr_random_numbers6 > arr_random_numbers7

array([[False,  True,  True, False, False],
       [False, False, False, False, False],
       [ True, False,  True, False,  True],
       [ True,  True, False,  True, False],
       [ True,  True,  True,  True,  True],
       [False,  True,  True,  True, False],
       [ True,  True, False, False, False],
       [ True, False,  True,  True, False],
       [False,  True,  True,  True,  True],
       [False,  True, False,  True,  True]])

What happens when you compare the arrays with `>`?

In [40]:
# Compare the two arrays with '>='
arr_random_numbers6 >= arr_random_numbers7

array([[ True,  True,  True, False, False],
       [False, False, False, False,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True, False,  True, False],
       [ True,  True,  True,  True,  True],
       [False,  True,  True,  True, False],
       [ True,  True, False,  True, False],
       [ True,  True,  True,  True, False],
       [False,  True,  True,  True,  True],
       [False,  True, False,  True,  True]])

In [41]:
# Find which elements of the first array are greater than 7
arr_random_numbers6 > 7

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False,  True, False, False,  True],
       [ True,  True, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [ True,  True, False, False, False],
       [ True, False,  True, False, False],
       [False,  True,  True, False,  True],
       [False, False, False, False,  True]])

In [42]:
# Which parts of each array are equal? (try using '==')
arr_random_numbers6 == arr_random_numbers7

array([[ True, False, False, False, False],
       [False, False, False, False,  True],
       [False,  True, False,  True, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False,  True, False],
       [False,  True, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [43]:
# Sort one of the arrays you just created in ascending order
np.sort(arr_random_numbers6)

array([[2, 2, 4, 5, 7],
       [0, 0, 2, 2, 4],
       [4, 6, 6, 8, 9],
       [0, 2, 6, 9, 9],
       [3, 3, 4, 6, 6],
       [1, 2, 3, 5, 6],
       [3, 4, 5, 8, 9],
       [0, 6, 6, 8, 9],
       [0, 3, 8, 8, 8],
       [2, 5, 6, 7, 8]])

In [44]:
# Sort the indexes of one of the arrays you just created
np.argsort(arr_random_numbers6)

array([[1, 4, 0, 3, 2],
       [0, 4, 1, 3, 2],
       [0, 2, 3, 4, 1],
       [4, 2, 3, 0, 1],
       [0, 1, 2, 3, 4],
       [4, 2, 0, 3, 1],
       [4, 2, 3, 1, 0],
       [4, 1, 3, 2, 0],
       [0, 3, 1, 2, 4],
       [0, 2, 1, 3, 4]])

In [45]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(arr_random_numbers6)

11

In [46]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(arr_random_numbers7)

1

In [47]:
# Find the indexes with the maximum values down the verticial axis
# of one of the arrays you created
np.argmax(arr_random_numbers6, axis=1)

array([2, 2, 1, 0, 3, 1, 0, 0, 1, 4])

In [48]:
# Find the indexes with the minimum values across the horizontal axis
# of one of the arrays you created
np.argmin(arr_random_numbers7, axis=1)

array([1, 4, 0, 1, 0, 2, 0, 3, 3, 1])

In [49]:
# Create an array of normally distributed random numbers
np.random.randn(3, 5)

array([[ 1.70660495,  0.87358942,  0.00914435, -0.3655393 ,  0.64908673],
       [-1.22287354,  0.53633603, -0.91469093,  0.62054822, -0.16093738],
       [-0.3882644 , -0.88551237, -0.35674503,  0.5561218 ,  1.04386061]])

In [50]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://docs.scipy.org/doc/numpy-1.15.0/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.